language: ruby

rvm:
  - 2.3.0

cache: bundler

services:
  - postgresql

before_script:
  - psql -c 'create database "web-barcamp-bangkhen7_test";' -U postgres

notifications:
  slack: barcamp2016-dev:oZACWcmGHQcWhnQTHCKhm4hf
